# Generated by Django 3.1.3 on 2021-01-14 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='photo_url',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.URLValidator(schemes=('http', 'https'))], verbose_name='Photo URL'),
        ),
    ]
