# Generated by Django 3.1.3 on 2021-01-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_change_app_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='notifications_status',
            field=models.CharField(choices=[('to be requested', 'to be requested'), ('allow', 'allow'), ('block', 'block')], default='to be requested', max_length=50),
        ),
    ]
