# Generated by Django 3.1.3 on 2021-01-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_appuser_notifications_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('word', 'word'), ('picture', 'picture')], default='word', max_length=30),
        ),
    ]
