# Generated by Django 3.1.3 on 2021-02-10 20:12

import django.db.models.deletion
import hashid_field.field
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_increase_max_length_of_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDefinition',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('word', 'word'), ('picture', 'picture')], default='word', max_length=30)),
                ('created_at', models.DateTimeField(editable=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='played_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
