# Generated by Django 3.1.3 on 2020-11-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_appgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Счет'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='vk_id',
            field=models.PositiveBigIntegerField(default=0, unique=True, verbose_name='VK ID'),
        ),
    ]
