# Generated by Django 3.1.3 on 2020-11-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20201121_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguagePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('visible', models.BooleanField(default=True)),
                ('english_word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='english_pair', to='game.word')),
                ('russian_word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='russian_pair', to='game.word')),
            ],
        ),
    ]
