# Generated by Django 3.1.3 on 2021-01-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='visits_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество визитов'),
        ),
    ]
