# Generated by Django 3.1.3 on 2021-01-16 07:53
# Fills users first_name, last_name and photo_url from VK data
from typing import List, Iterable

from django.db import migrations

from common.vk_utils import get_vk_api


def set_user_data(users: Iterable):
    users_data = get_vk_user_data([user.vk_id for user in users])
    i = 0
    for user in users:
        user.first_name = users_data[i]["first_name"]
        user.last_name = users_data[i]["last_name"]
        user.photo_url = users_data[i]["photo_200"]
        i += 1
        user.save()


def get_vk_user_data(vk_ids: List[int]) -> List[dict]:
    str_vk_ids = [str(vk_id) for vk_id in vk_ids]
    return get_vk_api().users.get(
        user_ids=",".join(str_vk_ids),
        fields="photo_200,first_name,last_name",
        lang="ru",
    )


def forward(apps, schema_editor):
    AppUser = apps.get_model("game", "AppUser")

    filtered_users = AppUser.objects.filter(is_staff=False, is_superuser=False)
    users_count = filtered_users.count()
    objects_in_batch = 50
    for i in range(0, users_count, objects_in_batch):
        users_batch = filtered_users[i : i + objects_in_batch]
        set_user_data(users_batch)


def backward(apps, schema_editor):
    AppUser = apps.get_model("game", "AppUser")
    AppUser.objects.filter(is_staff=False, is_superuser=False).update(
        first_name="", last_name="", photo_url=""
    )


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_appuser_photo_url"),
    ]

    operations = [migrations.RunPython(forward, backward)]
