# Generated by Django 3.1.3 on 2021-01-18 15:20

import django.contrib.auth.models
from django.db import migrations

import game.models.app_user


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_fill_user_vk_data'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('users', game.models.app_user.AppUserManager()),
            ],
        ),
    ]
