# Generated by Django 3.1.3 on 2021-01-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_game_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_word',
            new_name='question',
        ),
    ]
